version: 2.1
executors:
  node:
    docker:
      - image: cimg/node:20.19
  node-with-mongo:
    docker:
      - image: cimg/node:20.19
      - image: mongo:7.0
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  test:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: yarn test:ci
      - run: /bin/bash -c 'yarn audit --level=critical; [[ $? -ge 16 ]] && exit 1 || exit 0'

  test-example:
    executor: node-with-mongo
    steps:
      - attach_workspace:
          at: .
      - run: yarn ts-node examples/cli.ts up
      - run: yarn ts-node examples/cli.ts status
      - run: yarn ts-node examples/cli.ts down --all

  release:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: yarn release

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - test-example:
          requires:
            - build
      - release:
          context: dev
          requires:
            - test
            - test-example
          filters:
            branches:
              only: master
